# Generated by Django 4.1.6 on 2023-02-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_fragment'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='topic',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
