# Generated by Django 4.1.6 on 2023-02-10 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_apunte'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
