# Generated by Django 4.1.6 on 2023-02-10 09:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0011_delete_note'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apunte',
            new_name='Note',
        ),
    ]
